ARDUINO_VARIANT = d1_mini
ARDUINO_LIBS = FastLED
LOCAL_USER_LIBDIR = /home/torsten/Arduino/libraries
GLOBAL_USER_LIBDIR = /home/torsten/Arduino/hardware/esp8266com/esp8266/libraries
SERIAL_PORT = /dev/ttyACM0
SERIAL_BAUD = 115200
# uncomment this to use the 1M SPIFFS mapping
#SPIFFS_SIZE = 1
include ~/sw/Esp8266-Arduino-Makefile/espXArduino.mk

